language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/apache/incubator-openwhisk-cli/releases/download/latest/OpenWhisk_CLI-latest-linux-amd64.tgz | tar xz -C ~/.local/bin
script:
  - npm run lint
  - npm run test:unit
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh lookup && bash deploy.sh setgithubcheck && bash deploy.sh checker && bash deploy.sh signwebhook; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:integration; fi
deploy:
  provider: script
  script: bash deploy.sh lookup production && bash deploy.sh setgithubcheck production && bash deploy.sh checker production && bash deploy.sh signwebhook production
  on:
    branch: master
